---
requester: "The Auditors"
name: Cost Saving in the Cloud
description: >-
  We spend a lot of money in the cloud. We should spend less.
  As a team we should review the the cost explorer reports and prioritise
  the three biggest savings we can make, as a percentage of total expense,
  and fix all three of them in this iteration.
